version: "3"
services:
       jobster-api:
           container_name: jobster-api
           image: latest123/login-app
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'